### ISSUE TITLE
Проблемы со слаком

### ISSUE THREAD

**Issue by rukivboki** [terazumova/isa-fd-team-2#29]
Ребят, если вы в созвоне - давайте через зум? Слак отказался работать со всех устройств @Neo1338 @terazumova @AntipAntipov @Feduchio

**Comment by cursed-friendship** [comment]
Подключиться к конференции Zoom
https://us05web.zoom.us/j/85619625195?pwd=NXMzcUNhTDZBdWp1V2JQQ2pnWVczdz09

Идентификатор конференции: 856 1962 5195
Код доступа: q9WtNh
